apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jenkins-agent-persistent
  name: maven-cache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  storageClassName: standard-rwx